import { createClient, type SupabaseClient } from "npm:@supabase/supabase-js@2.116.0";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const LEGACY="https://script.google.com/macros/s/AKfycbw0DVegfMkhL2abjfDn7RJPS2zH_zAmI7DVHPO_tZdF2qMED04lff62hfWl91TV9D0/exec";
const SHEET="https://docs.google.com/spreadsheets/d/1ve-CErmnMplWxTgJqmoanb182-cYeITJuKud_Ks8EAQ/edit";
const MIGRATION="apps_script_v7";
const ROLES=new Set(["admin","owner","desarrollador","creador","jefatura","jefe","jefe_turno"]);
const OWNER="mdcarlosherrera@gmail.com";
const PRIORITIES=new Set(["Baja","Media","Alta","Crítica"]);
type M=Record<string,unknown>;
type Auth={email:string;name:string;role:string;token:string;anonKey:string;admin:SupabaseClient};
class E extends Error{status:number;constructor(status:number,message:string){super(message);this.status=status}}
const txt=(v:unknown,n=1200)=>String(v??"").replace(/\u0000/g,"").trim().slice(0,n);
const json=(body:M,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const role=(v:unknown)=>txt(v,100).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
function rut(v:unknown){const c=String(v??"").toUpperCase().replace(/[^0-9K]/g,"");return c.length<2?"":`${c.slice(0,-1)}-${c.slice(-1)}`}
function validRut(v:unknown){const c=String(v??"").toUpperCase().replace(/[^0-9K]/g,"");if(!/^\d{7,8}[0-9K]$/.test(c))return false;let s=0,m=2;for(let i=c.length-2;i>=0;i--){s+=Number(c[i])*m;m=m===7?2:m+1}const r=11-(s%11),e=r===11?"0":r===10?"K":String(r);return c.slice(-1)===e}
function chileDate(){const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
const chileYear=()=>Number(chileDate().slice(0,4));
function dateOnly(v:unknown){const s=txt(v,30),m=s.match(/^\d{4}-\d{2}-\d{2}/);return m?m[0]:null}
function dateTime(v:unknown,f:string){const s=txt(v,80);if(!s)return f;const d=new Date(s);return Number.isNaN(d.getTime())?f:d.toISOString()}
function env(){const supabaseUrl=Deno.env.get("SUPABASE_URL")||"",anonKey=Deno.env.get("SUPABASE_ANON_KEY")||"",serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!supabaseUrl||!anonKey||!serviceKey)throw new E(500,"Faltan variables internas de Supabase.");return{supabaseUrl,anonKey,serviceKey}}
async function body(req:Request){const s=await req.text();if(new TextEncoder().encode(s).byteLength>100000)throw new E(413,"Solicitud demasiado grande.");if(!s.trim())return{} as M;try{const p=JSON.parse(s);return p&&typeof p==="object"?p as M:{}}catch{throw new E(400,"Solicitud JSON inválida.")}}
function sanitize(raw:unknown,actor:{email?:string;name?:string}={},now=new Date().toISOString()){const s=raw&&typeof raw==="object"?raw as M:{};const v=(k:string)=>txt(s[k],["resumen_clinico","observaciones","gestion_solicitada","proximo_paso"].includes(k)?5000:1200);const x:Record<string,string|null>={numero_solicitud:v("numero_solicitud"),id:v("id"),fecha_registro:dateTime(s.fecha_registro,now),registrado_por:v("registrado_por"),medico_solicitante:v("medico_solicitante"),rut_medico:rut(s.rut_medico),paciente:v("paciente"),run:v("run"),edad:v("edad"),telefono:v("telefono"),ubicacion:v("ubicacion")||"Urgencia Adulto",flujo:v("flujo"),motivo:v("motivo"),resumen_clinico:v("resumen_clinico"),gestion_solicitada:v("gestion_solicitada"),prioridad:v("prioridad")||"Alta",origen:v("origen")||"MASTER Urgencias HPH",estado:v("estado")||"Pendiente",resuelto:v("resuelto")||"Pendiente",proximo_paso:v("proximo_paso")||"Pendiente de revisión por jefatura",responsable:v("responsable")||"Jefatura",fecha_compromiso:dateOnly(s.fecha_compromiso),fecha_resolucion:dateOnly(s.fecha_resolucion),observaciones:v("observaciones"),actualizado:now};x.medico_solicitante=x.medico_solicitante||x.registrado_por||actor.name||actor.email||"";x.registrado_por=x.registrado_por||x.medico_solicitante||actor.email||actor.name||"";return x}
function validate(x:Record<string,string|null>,doctor=false){for(const[k,l]of [["paciente","nombre del paciente"],["run","RUN del paciente"],["flujo","especialidad o prestación requerida"],["resumen_clinico","resumen clínico"],["gestion_solicitada","gestión solicitada"],["medico_solicitante","médico solicitante"]] as [string,string][])if(!txt(x[k]))throw new E(400,`Falta ${l}.`);if(doctor&&!txt(x.rut_medico))throw new E(400,"Falta RUT del médico.");if(!PRIORITIES.has(String(x.prioridad)))throw new E(400,"Prioridad inválida.")}
async function auth(req:Request,b:M):Promise<Auth>{const{supabaseUrl,anonKey,serviceKey}=env();const h=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim(),token=txt(b.accessToken,10000)||h;if(!token)throw new E(401,"Sesión de Jefatura no disponible. Vuelve a iniciar sesión.");const u=createClient(supabaseUrl,anonKey,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}}),admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});const{data:ud,error:ue}=await u.auth.getUser(token),email=txt(ud?.user?.email,320).toLowerCase();if(ue||!email)throw new E(401,"La sesión de Jefatura venció o no es válida.");const{data:p,error:pe}=await admin.from("crs_admins").select("email,display_name,role,active").eq("email",email).maybeSingle();if(pe)throw new E(500,"No se pudo comprobar el permiso de Jefatura.");const r=role(p?.role);if(!p||p.active===false||(!ROLES.has(r)&&email!==OWNER))throw new E(403,"Usuario sin permiso activo de Jefatura.");return{email,name:txt(p.display_name,200)||email,role:r,token,anonKey,admin}}
async function history(admin:SupabaseClient,id:string,action:string,actor:string,detail:string){const{error}=await admin.from("crs_patient_history").insert({case_id:id,accion:action,actor,detalle:txt(detail,5000)});if(error)console.error("history",error.message)}
async function counter(admin:SupabaseClient,year:number,min:number){const{data,error}=await admin.from("crs_patient_case_counters").select("last_number").eq("year",year).maybeSingle();if(error)throw error;if(Number(data?.last_number||0)>=min)return;const{error:e}=await admin.from("crs_patient_case_counters").upsert({year,last_number:min},{onConflict:"year"});if(e)throw e}
async function bootstrap(a:Auth){const{data:m,error:me}=await a.admin.from("crs_patient_migration_state").select("completed_at").eq("migration_key",MIGRATION).maybeSingle();if(me)throw new E(500,"No se pudo comprobar la migración.");if(m?.completed_at)return;let old:M;try{const r=await fetch(LEGACY,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"listPatientCases",accessToken:a.token,supabaseAnonKey:a.anonKey})});old=JSON.parse(await r.text())}catch(e){throw new E(502,`No se pudo leer el respaldo histórico de Apps Script: ${e instanceof Error?e.message:String(e)}`)}if(old.ok!==true||!Array.isArray(old.cases))throw new E(502,txt(old.error,500)||"Apps Script no entregó los casos históricos.");const now=new Date().toISOString(),rows=(old.cases as unknown[]).map(r=>{const x=sanitize(r,{},now);x.fecha_registro=dateTime((r as M).fecha_registro,now);x.actualizado=dateTime((r as M).actualizado,String(x.fecha_registro||now));return x});for(let i=0;i<rows.length;i+=200){const{error}=await a.admin.from("crs_patient_cases").upsert(rows.slice(i,i+200),{onConflict:"id"});if(error)throw new E(500,`No se pudieron migrar los casos históricos: ${error.message}`)}const mx=new Map<number,number>();for(const r of rows){const z=String(r.numero_solicitud||"").match(/^GA-(\d{4})-(\d+)$/);if(z)mx.set(Number(z[1]),Math.max(mx.get(Number(z[1]))||0,Number(z[2])))}for(const[y,n]of mx)await counter(a.admin,y,n);const{error:se}=await a.admin.from("crs_patient_migration_state").upsert({migration_key:MIGRATION,completed_at:now,detail:{source:"apps-script-v7",legacySpreadsheetUrl:SHEET,cases:rows.length,note:"El historial detallado anterior permanece archivado en Google Sheets."}},{onConflict:"migration_key"});if(se)throw new E(500,"Los casos se migraron, pero no se pudo cerrar la migración.")}
async function next(admin:SupabaseClient){const{data,error}=await admin.rpc("crs_next_patient_case_number",{p_year:chileYear()});if(error||!data)throw new E(500,"No se pudo generar el número de solicitud.");return String(data)}
const id=()=>`caso-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;
async function doctor(admin:SupabaseClient,r:unknown,n:unknown,now:string){const rr=rut(r);if(!validRut(rr))throw new E(400,"RUT del médico inválido.");let{data:d,error}=await admin.from("crs_patient_doctors").select("rut_medico,nombre,activo").eq("rut_medico",rr).maybeSingle();if(error)throw new E(500,"No se pudo validar al médico solicitante.");if(d){if(d.activo===false)throw new E(403,"El RUT del médico está deshabilitado. Contacta a Jefatura.");return{d,registered:false}}const name=txt(n,200);if(!name)throw new E(400,"Falta el nombre del médico solicitante.");const ins=await admin.from("crs_patient_doctors").insert({rut_medico:rr,nombre:name,activo:true,fecha_registro:now,total_solicitudes:0});if(ins.error&&ins.error.code!=="23505")throw new E(500,"No se pudo registrar al médico solicitante.");({data:d,error}=await admin.from("crs_patient_doctors").select("rut_medico,nombre,activo").eq("rut_medico",rr).single());if(error||!d)throw new E(500,"No se pudo confirmar el registro del médico.");if(d.activo===false)throw new E(403,"El RUT del médico está deshabilitado. Contacta a Jefatura.");return{d,registered:!ins.error}}
async function savePublic(b:M){const{supabaseUrl,serviceKey}=env(),admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),now=new Date().toISOString(),input=b.case&&typeof b.case==="object"?b.case as M:{},q=await doctor(admin,b.doctorRut||input.rut_medico,input.medico_solicitante,now),x=sanitize(input,{},now);x.rut_medico=rut(q.d.rut_medico);x.medico_solicitante=txt(q.d.nombre,200);x.registrado_por=`${x.medico_solicitante} (${x.rut_medico})`;x.numero_solicitud=await next(admin);x.id=x.id||id();x.fecha_registro=now;x.estado="Pendiente";x.resuelto="Pendiente";x.proximo_paso="Pendiente de revisión por jefatura";x.responsable="Jefatura";x.actualizado=now;validate(x,true);const{data:s,error}=await admin.from("crs_patient_cases").insert(x).select("*").single();if(error||!s)throw new E(500,`No se pudo registrar la solicitud${error?`: ${error.message}`:"."}`);await history(admin,s.id,"Solicitud creada",String(s.registrado_por||""),q.registered?"Registro automático del médico por RUT y creación de solicitud":"Registro público por médico ya habilitado");return json({ok:true,case:s,numero_solicitud:s.numero_solicitud,doctor_registered:q.registered,doctor:{rut_medico:q.d.rut_medico,nombre:q.d.nombre},message:`Solicitud ${s.numero_solicitud} registrada correctamente.`})}
async function all(admin:SupabaseClient){const out:unknown[]=[];for(let i=0;i<10000;i+=1000){const{data,error}=await admin.from("crs_patient_cases").select("*").order("fecha_registro",{ascending:false}).range(i,i+999);if(error)throw new E(500,`No se pudieron cargar los casos: ${error.message}`);out.push(...(data||[]));if(!data||data.length<1000)break}return out}
async function list(a:Auth){await bootstrap(a);return json({ok:true,cases:await all(a.admin),spreadsheetUrl:SHEET,backend:"supabase",viewer:{email:a.email,role:a.role}})}
async function save(a:Auth,b:M){await bootstrap(a);const now=new Date().toISOString(),input=b.case&&typeof b.case==="object"?b.case as M:{},x=sanitize(input,{email:a.email,name:a.name},now);validate(x,false);x.numero_solicitud=x.numero_solicitud||await next(a.admin);x.id=x.id||id();x.registrado_por=x.registrado_por||a.email;x.actualizado=now;const{data:s,error}=await a.admin.from("crs_patient_cases").insert(x).select("*").single();if(error||!s)throw new E(500,`No se pudo guardar el caso${error?`: ${error.message}`:"."}`);await history(a.admin,s.id,"Solicitud creada por Jefatura",a.email,"Registro protegido en Supabase");return json({ok:true,case:s,spreadsheetUrl:SHEET,backend:"supabase"})}
async function update(a:Auth,b:M){await bootstrap(a);const caseId=txt(b.id,300);if(!caseId)throw new E(400,"Falta el identificador del caso.");const{data:c,error:ce}=await a.admin.from("crs_patient_cases").select("*").eq("id",caseId).maybeSingle();if(ce)throw new E(500,"No se pudo cargar el caso.");if(!c)throw new E(404,"Caso no encontrado.");const p=b.patch&&typeof b.patch==="object"?b.patch as M:{},allow=["estado","resuelto","proximo_paso","responsable","fecha_compromiso","fecha_resolucion","observaciones","prioridad"],ap:M={};for(const k of allow)if(Object.prototype.hasOwnProperty.call(p,k))ap[k]=p[k];const now=new Date().toISOString(),x=sanitize({...c,...ap},{email:a.email,name:a.name},now);x.id=c.id;x.numero_solicitud=c.numero_solicitud;x.fecha_registro=c.fecha_registro;x.registrado_por=c.registrado_por;x.actualizado=now;if((x.estado==="Gestionada"||x.estado==="Cerrada")&&!x.fecha_resolucion)x.fecha_resolucion=chileDate();validate(x,false);const{data:s,error}=await a.admin.from("crs_patient_cases").update(x).eq("id",caseId).select("*").single();if(error||!s)throw new E(500,`No se pudo actualizar el caso${error?`: ${error.message}`:"."}`);await history(a.admin,caseId,"Seguimiento actualizado",a.email,JSON.stringify(ap).slice(0,4000));return json({ok:true,case:s,spreadsheetUrl:SHEET,backend:"supabase"})}

export default {async fetch(req:Request):Promise<Response>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method==="GET")return json({ok:true,service:"MASTER Urgencias HPH - Gestión pacientes",version:8,backend:"supabase"});if(req.method!=="POST")return json({ok:false,error:"Método no permitido."},405);try{const b=await body(req),action=txt(b.action,100);if(action==="savePublicPatientCase")return await savePublic(b);if(action==="login")return json({ok:false,error:"El ingreso Google legacy está desactivado. Usa Jefatura con Supabase."},400);const a=await auth(req,b);if(action==="listPatientCases")return await list(a);if(action==="savePatientCase")return await save(a,b);if(action==="updatePatientCase")return await update(a,b);return json({ok:false,error:"Acción no reconocida",action},400)}catch(e){console.error(e);return e instanceof E?json({ok:false,error:e.message},e.status):json({ok:false,error:e instanceof Error?e.message:String(e)},500)}}};
